---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uqqffkqc/public_html/
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R icon $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
